### ISSUE TITLE
getting error if using different image from test 

### ISSUE THREAD

**Issue by segalinc** [akisatok/pySaliencyMap#4]
Hello, 

I am trying to use this repo but when I use my images I always get this error if the image is smaller than 260x260

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/main.py", line 32, in <module>
    saliency_map = sm.SMGetSM(img)
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/pySaliencyMap.py", line 242, in SMGetSM
    ICM = self.ICMGetCM(IFM)
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/pySaliencyMap.py", line 196, in ICMGetCM
    NIFM = self.normalizeFeatureMaps(IFM)
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/pySaliencyMap.py", line 190, in normalizeFeatureMaps
    normalizedImage = self.SMNormalization(FM[i])
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/pySaliencyMap.py", line 183, in SMNormalization
    lmaxmean = self.SMAvgLocalMax(dst)
  File "/Users/segac006/Desktop/Projects/smile_classifier/util_exp/pySaliencyMap/pySaliencyMap.py", line 179, in SMAvgLocalMax
    return lmaxmean / numlocal
ZeroDivisionError: division by zero

**Comment by akisato-** [comment]
Since Itti's saliency map employs Gaussian pyramids, input images should be larger than 255x255. However, I think that it is no problem if your image has a size of 260x260.

**Comment by datalowe** [comment]
I don't know much about the underlying algorithms, so it might be inappropriate, but there is a way to force pySaliencyMap to work with smaller images, and it seems to work OK, at least for images just below the 255 limit. Here's the original image I used and the result I got:

![book-3603964_640](https://user-images.githubusercontent.com/65363390/120472220-e8f01380-c3a5-11eb-9e88-851b0497cc9b.png)

![book-3603964_640](https://user-images.githubusercontent.com/65363390/120472244-ef7e8b00-c3a5-11eb-8fae-696a33e17af0.png)

In order to force this behavior, one can, in _'pySaliencyMap.py'_ around line 170, change the code to this (additions are in the NEW section):

```py
    ## computing an average of local maxima
    def SMAvgLocalMax(self, src):
        # size
        stepsize = pySaliencyMapDefs.default_step_local
        width = src.shape[1]
        height = src.shape[0]
        # find local maxima
        numlocal = 0
        lmaxmean = 0
        # NEW
        if height <= stepsize:
            stepsize = int(height / 2)
        if width <= stepsize:
            stepsize = int(width / 2)
        # END NEW
        for y in range(0, height-stepsize, stepsize):
            for x in range(0, width-stepsize, stepsize):
                localimg = src[y:y+stepsize, x:x+stepsize]
                lmin, lmax, dummy1, dummy2 = cv2.minMaxLoc(localimg)
                lmaxmean += lmax
                numlocal += 1
        # averaging over all the local regions
        return lmaxmean / numlocal
```
Again, I don't really know how this affects the algorithm, so no one should use the results directly for eg research. But if you're like me, and only use the saliency maps for 'manually' comparing images in order to find the most fitting ones, I'm guessing this might be fine.

**Comment by akisatok** [comment]
@datalowe Sorry for the late reply, the image size limit is mainly due to

1. the use of cv2.pyrdown in FMCreateGaussianPyr (Line 44-46 in pySaliencyMap.py)
2. the size of local regions, namely the step size as you mentioned,  for taking local maxima 

Although I followed the guideline presented in the original paper [Itti+ TPAMI1998], the above two issues can be solved by a few revisions. Your example might be a possible solution for the second issue. The first one can be fixed by replacing cv2.pyrdown with a combination of Gaussian filtering and (adaptive) resizing.

But, I think that the easiest way is to enlarge input images to the ones larger than 256x256, compute saliency maps, and shrink them to the original image size.
